[11.0] Helpdesk Rating Module
OCA/helpdesk pull request #100
Opened 2019-10-03 08:03 UTC by SamuelDomatix

This module gives the possibility of rate by the customer, the assistance received on their tickets.

- Added new menu **Helpdesk / Reports / Customer Rating**
- In the ticket kanban view:
    - Added the percentage of positive ratings of each ticket.
    - Added a new menu on each ticket with its own ratings.
- In the ticket form view:
    - Added new field in the ticket form view to select the type of rating.
    - Added a smartbutton in the ticket form view with all the ratings of the ticket.
- Added new field **Rating Email Template** in stages.
- Modified the tree view of the stages to show the rating email template.
- Created a rating email template.

2019-10-03 10:20 UTC, emagdalenaC2i requested changes
I think OCA must be as Authors too
See https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2019-10-03 10:20 UTC, emagdalenaC2i commented on helpdesk_mgmt_rating/__manifest__.py
> +    'author': 'Domatix',
```suggestion
    'author': 'Domatix, Odoo Community Association (OCA)',
```

2019-10-03 10:42 UTC, SamuelDomatix commented on helpdesk_mgmt_rating/__manifest__.py
> +    'author': 'Domatix',
Changed!

2019-10-04 11:07 UTC, catalin-domatix approved these changes

2019-10-04 11:08 UTC, alvaro-domatix approved these changes

2020-01-29 23:43 UTC, rafaelbn approved these changes
:+1:

2020-01-29 23:52 UTC, emagdalenaC2i approved these changes

2020-01-30 00:02 UTC, pedrobaeza commented on helpdesk_mgmt_rating/__manifest__.py
> +    'category': 'Productivity',
Please put the same category than the main module

2020-07-19 08:47 UTC, dreispt commented
/ocabot merge nobump

2020-07-19 08:55 UTC, merged