[ADD-->IMP] Relationship between Category and Team
OCA/helpdesk pull request #133
Opened 2020-06-08 20:56 UTC by juandanielp24

A relationship between category and team is added. So when the user creates a ticket and selects the category, it relates it to the corresponding team and appears on the board.

![image](https://user-images.githubusercontent.com/62858972/84079614-3f07c200-a9b1-11ea-8de1-7d20998b4215.png)

![image](https://user-images.githubusercontent.com/62858972/84079635-45963980-a9b1-11ea-936c-335d20ffa5e8.png)

The team is assigned automatically

2020-06-08 21:03 UTC, emagdalenaC2i commented
I mean to rename as "[IMP] Relationship between Category and Team" because I think it is an improvement and not something to ADD (a new module)

2020-06-08 21:09 UTC, juandanielp24 commented
@emagdalenaC2i 
ok, i already changed the name

2020-06-18 13:35 UTC, DarioLodeiros requested changes
this PR is mixed with #132

2020-06-18 13:35 UTC, DarioLodeiros commented on helpdesk_mgmt/controllers/main.py
> +            "team_id": request.env["helpdesk.ticket.category"]
how does this relate to the PR topic?

2020-06-18 13:35 UTC, DarioLodeiros commented on helpdesk_mgmt/controllers/main.py
> +            .sudo()
Idem

2020-06-18 13:35 UTC, DarioLodeiros commented on helpdesk_mgmt/controllers/myaccount.py
> +        file = (
and Idem

2020-06-18 13:35 UTC, DarioLodeiros commented on helpdesk_mgmt/views/helpdesk_ticket_templates.xml
> +                                    <strong>Attachments:</strong>
and this one too

2022-01-09 12:17 UTC, closed without merging