[IMP] helpdesk_mgmt: add text input in ticket list searchbar
OCA/helpdesk pull request #147
Opened 2020-07-13 15:01 UTC by luffah

See https://github.com/OCA/helpdesk/issues/64 as original issue.
See https://github.com/OCA/helpdesk/pull/69 for v11.0.
See https://github.com/OCA/helpdesk/pull/141 for v12.0.

This PR add search bar text input to portal ticket list.
Searchable fields are : name; description; user; category; (optionally message content)
2 meta fields extend searchable fields : All (lookup all searchable fields); Content (name + description + optionally message content) 

Searching in message content is enabled by installing the module [base_search_mail_content](https://github.com/OCA/social/tree/13.0/base_search_mail_content).

2020-08-23 13:58 UTC, flachica requested changes

2020-08-23 13:58 UTC, flachica commented on helpdesk_mgmt/controllers/myaccount.py
> +            ('name', '=', 'base_search_mail_content')])
You must put this dependence in <repo_root>/oca_dependencies.txt

2020-08-23 14:00 UTC, flachica commented
If yoy run pre-commit run -a you can solve [this](https://travis-ci.com/github/OCA/helpdesk/jobs/360492181#L278)

Functional test OK

Thanks for your work

2020-12-03 12:21 UTC, luffah commented
> If yoy run pre-commit run -a you can solve [this](https://travis-ci.com/github/OCA/helpdesk/jobs/360492181#L278)

yoy ? is it a tool ;)

2020-12-03 12:52 UTC, emagdalenaC2i commented
@luffah See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

2021-12-13 10:42 UTC, luffah commented
I was looking again on this PR.
If i understand well, it is blocked because a test is missing.

2021-12-13 11:12 UTC, luffah commented on helpdesk_mgmt/controllers/myaccount.py
> +            ('name', '=', 'base_search_mail_content')])
added base_search_mail_content in oca_dependencies.txt

2021-12-13 11:13 UTC, luffah commented
merged with most recent changes…
oh crap, i shall redo a new PR…

2021-12-13 11:13 UTC, closed without merging