[12.0][ADD] helpdesk_mgmt_timesheet
OCA/helpdesk pull request #151
Opened 2020-07-28 17:13 UTC by dalonsod

This module adds timesheet support for helpdesk tickets. 

Supersedes #121 . Original commits were squashed for cleaning purposes in a single one. Since original PR, these changes have been made:
- rebased in order to retrieve `helpdesk_mgmt_project` dependency.
- changed manifest dependencies and `account.analytic.account` references had become `project.project` ones.
- some file renaming.
- added full ticket support (menu, views, permissions) to `account.analytic.line` model.
- improved `search` and `tree` views for tickets.
- added demo data.

It seems a lot of changes, but original work is still present :-)

2020-07-29 14:34 UTC, dalonsod commented
@oscars8a @EDallas89 @marcelsavegnago could you review? Thanks!

@DarioLodeiros runbot shows an error status, but it's actually working and I'm not able to find out any error message. Could you check?

To everyone, I've slightly changed ticket requirements to the "allow timesheet" functionality. Since `helpdesk_mgmt_project` already adds `project_id` to a to ticket, and that's actually the main requirement to timesheet management, if present in a ticket automatically timesheets are allowed. Then, I redefined "allow timesheet" for helpdesk teams: now is used to make the project required in a ticket. What dou you think?

2020-07-29 16:04 UTC, DarioLodeiros commented
I can't see the problem, @pedrobaeza can you review this runbot fail? and coverage?

2020-07-30 06:04 UTC, marcelsavegnago reviewed
The task is being created without linking to the product. I believe it is important to take on the project that is defined in the ticket.

2020-07-30 07:59 UTC, hbrunn requested changes
runbot is red because of


```
2020-07-30 04:07:02,187 161 WARNING openerp_test odoo.models: project.project.create() with unknown fields: project_id
```

in the all logs. Coverage only runs when both travis and runbot succeed

2020-07-30 07:59 UTC, hbrunn commented on helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
> +                </button>
why do we need this button?

2020-07-30 07:59 UTC, hbrunn commented on helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
> +                <page string="Timesheets" attrs="{'invisible':[('project_id', '=', False)]}">
this should be restricted to timesheet users I think

2020-07-30 07:59 UTC, hbrunn commented on helpdesk_mgmt_timesheet/models/hr_timesheet.py
> +    )
I suggest to add a constraint enforcing that this belongs to the project

2020-07-30 07:59 UTC, hbrunn commented on helpdesk_mgmt_timesheet/security/helpdesk_mgmt_timesheet_security.xml
> +            <field name="implied_ids" eval="[(4, ref('hr_timesheet.group_hr_timesheet_user'))]"/>
I don't think we should have that. When we want a user to be able to record time on tickets, they should have both groups assigned manually

2020-07-30 07:59 UTC, hbrunn commented on helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
> +                <filter name="overtimed" string="Overtimed"
I don't know this word. How about 'late'?

2020-07-30 08:24 UTC, DarioLodeiros commented on helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
> +                </button>
+1

2020-07-30 12:57 UTC, dalonsod commented on helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
> +                </button>
OK, I'll review it, and remove if does not make sense. This development started with some initial functionalities, I'd preserved some of them without knowing their purpose or intention.

2020-07-30 12:59 UTC, dalonsod commented on helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
> +                <page string="Timesheets" attrs="{'invisible':[('project_id', '=', False)]}">
I agree, specially if helpdesk and timesheet user security groups are not linked

2020-07-30 13:00 UTC, dalonsod commented on helpdesk_mgmt_timesheet/models/hr_timesheet.py
> +    )
I think I put it the view, I'll change it to the field definition if possible

2020-07-30 13:04 UTC, dalonsod commented on helpdesk_mgmt_timesheet/security/helpdesk_mgmt_timesheet_security.xml
> +            <field name="implied_ids" eval="[(4, ref('hr_timesheet.group_hr_timesheet_user'))]"/>
Yes, I had a big doubt with this, removing this inheritance, we can maintain both ticket users with and without timesheet access. I'll remove it and review every timesheet access within this module.

2020-07-30 13:06 UTC, dalonsod commented on helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml
> +                <filter name="overtimed" string="Overtimed"
Sorry for my english :( I was looking for "this ticket has extra time" in a single word

2020-07-30 13:07 UTC, dalonsod commented
> 
> 
> runbot is red because of
> 
> ```
> 2020-07-30 04:07:02,187 161 WARNING openerp_test odoo.models: project.project.create() with unknown fields: project_id
> ```
> 
> in the all logs. Coverage only runs when both travis and runbot succeed

I'll look for this reference on tests, thanks!

2020-07-30 13:14 UTC, dalonsod commented
> 
> 
> The task is being created without linking to the product. I believe it is important to take on the project that is defined in the ticket.

For _product_, do you really want to say "project"? Anyway, project and task management don't belong to this module. Maybe you've detected a problem related to `helpdesk_mgmt_project` module, if I'm right.

2020-07-30 16:44 UTC, dalonsod commented on helpdesk_mgmt_timesheet/views/helpdesk_team_view.xml
> +                </button>
Button removed

2020-07-30 16:44 UTC, dalonsod commented on helpdesk_mgmt_timesheet/models/hr_timesheet.py
> +    )
Done!

2020-07-30 16:46 UTC, dalonsod commented
@hbrunn comments attended

2020-07-30 18:34 UTC, marcelsavegnago commented
> For _product_, do you really want to say "project"? Anyway, project and task management don't belong to this module. Maybe you've detected a problem related to `helpdesk_mgmt_project` module, if I'm right

@dalonsod You're right, I got confused with scope. In fact it would be something in the helpdesk_mgmt_project

2020-07-31 11:50 UTC, dalonsod commented
> @dalonsod You're right, I got confused with scope. In fact it would be something in the helpdesk_mgmt_project.
> 
> Yes, i really want say project..

Exactly. Open #152

2020-08-04 14:25 UTC, dalonsod commented
@DarioLodeiros I've found an error when accessing timesheets for a user without permissions in Helpdesk, due to `search` view additions (`filter` nodes referring `ticket_id`) to `account.analytic.line`. There are two different ways to solve this: adding `groups="helpdesk_mgmt.group_helpdesk_user"` to every filter definition within the view, or forcing access rights for the whole view to the group above. What is the best approach, is there any OCA convention for this? Form and tree views work correctly without any change.

2020-08-18 09:57 UTC, dalonsod commented
Any news on this? If approved, I could also migrate it to v13. Thanks!

2020-08-19 01:01 UTC, marcelsavegnago approved these changes
Funcional review Ok

2020-08-20 12:33 UTC, AntoniRomera approved these changes

2020-08-21 08:58 UTC, DarioLodeiros approved these changes
Functional y Technical Review

2020-08-22 19:27 UTC, flachica approved these changes

2020-08-22 19:36 UTC, DarioLodeiros commented
/ocabot merge minor

2020-08-22 19:45 UTC, merged

2020-08-23 09:48 UTC, flachica commented
> 13.

I migrate to 13.0. I need it

2020-08-24 16:00 UTC, dalonsod commented
@DarioLodeiros this addon is still unavailable to be translated: https://translation.odoo-community.org/projects/helpdesk-12-0/ . However, in v13 it's OK. Could you check?

2020-08-31 06:52 UTC, dalonsod commented
> 
> 
> @DarioLodeiros this addon is still unavailable to be translated: https://translation.odoo-community.org/projects/helpdesk-12-0/ . However, in v13 it's OK. Could you check?

@DarioLodeiros any news on this?