[13.0][ADD] helpdesk_mgmt_sla 13.0.1.1.0
OCA/helpdesk pull request #157
Opened 2020-08-29 09:56 UTC by hgarridoco

This PR aims to add SLA.

Last try to PR from this repo was wrong because is my first PR to OCA and I failed.

2020-08-29 15:39 UTC, marcelsavegnago reviewed
Great job. However, here are some comments.

- The SLA record could allow you to be associated with multiple teams.
- In the team registration, it would include a tab to select the applied SLAs or even create a new one.
- Including demo data is also a good thing.
- I didn't see data about the SLA on the ticket form.
- After everything is evaluated and reviewed, I would appreciate it if you could do a PR for the V12 as well.

I noticed that you are calculating / changing the SLA expiration date on closed and canceled tickets.
![image](https://user-images.githubusercontent.com/3595132/91640523-8d4ac100-e9f4-11ea-9d93-e54f53c859c3.png)

2020-08-29 15:43 UTC, hgarridoco commented
@marcelsavegnago I'll make your comments, you're right!

2020-08-30 11:34 UTC, hgarridoco commented
@marcelsavegnago check it out!

2020-09-16 08:21 UTC, marcelsavegnago commented
@hgarridoco it'd be good to have a few unit tests :)

2020-09-16 08:25 UTC, marcelsavegnago reviewed
@hgarridoco it'd be good to have a few unit tests :)

2020-10-01 07:49 UTC, DarioLodeiros commented
@hgarridoco can you review the create_datetime field on create method? Travis fails becouse this field does not exist

2020-10-01 10:42 UTC, DarioLodeiros requested changes
The code still has bugs, you can check them in the travis log

2020-10-01 10:42 UTC, DarioLodeiros commented on helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
> +                "team_id": [(6, 0, [self.team_id.id])],
Integer Field, not recordset

2020-10-01 14:13 UTC, hgarridoco commented on helpdesk_mgmt_sla/tests/test_helpdesk_mgmt_sla.py
> +                "team_id": [(6, 0, [self.team_id.id])],
Changed!

2020-10-23 13:58 UTC, hgarridoco commented
@DarioLodeiros please check this new commit and review it.
@marcelsavegnago sorry about my delay, lot of work!

2020-10-23 15:27 UTC, marcelsavegnago approved these changes
LGTM

2020-10-23 15:30 UTC, marcelsavegnago approved these changes
LGTM

2020-11-08 13:50 UTC, Saran440 reviewed
Functional Test.
- SLA Deadline is generate mistake. If I config SLA is 2 hours, it generate SLA Deadline + 1 day and 16.00 only.

- I config SLA Reach Stage is `in progress`, should it start SLA when stage ticket is `in progress` ? but I create new ticket stage `new` it start SLA deadline or I mistake something?
![Selection_006](https://user-images.githubusercontent.com/20896369/98466704-dcd31780-2203-11eb-9004-5cbc64481410.png)


**Results**
![Selection_007](https://user-images.githubusercontent.com/20896369/98466710-e2306200-2203-11eb-9746-1b5101dae3c7.png)

2020-11-15 18:43 UTC, hgarridoco commented
> Functional Test.
> 
> * SLA Deadline is generate mistake. If I config SLA is 2 hours, it generate SLA Deadline + 1 day and 16.00 only.
> * I config SLA Reach Stage is `in progress`, should it start SLA when stage ticket is `in progress` ? but I create new ticket stage `new` it start SLA deadline or I mistake something?
>   ![Selection_006](https://user-images.githubusercontent.com/20896369/98466704-dcd31780-2203-11eb-9004-5cbc64481410.png)
> 
> **Results**
> ![Selection_007](https://user-images.githubusercontent.com/20896369/98466710-e2306200-2203-11eb-9746-1b5101dae3c7.png)

Hi,

Be careful to check if deadline is correct because the code check resource calender to calculate it. For example, if some ticket arrive at 12 pm and your resource calendar is from 8 am to 17 pm, and your deadline horus are 2, deadline will be set at 10 am.

About reach stage is which stage you need to move this ticket to not calculate deadline. For example, if I need that my tickets arrives at  "In progress" in 2 hours or less, I will set this stage at reach stage.

This module calculate SLA like Odoo EE.

Sorry about if I take some tome to answer your question or problems, I'm so bussy.

2021-06-16 16:02 UTC, hgarridoco commented
@DarioLodeiros can you review it again?

2021-08-21 19:30 UTC, spgevers approved these changes
Functional test successful.

2021-08-24 00:11 UTC, marcelsavegnago commented
ping @OCA/helpdesk-maintainers

2021-08-24 00:20 UTC, marcelsavegnago commented
@hgarridoco can you do squash commits ?

2021-08-24 06:59 UTC, Saran440 approved these changes
Okay I see. Functional Test :+1:

2021-08-24 07:09 UTC, hgarridoco commented
> @hgarridoco can you squash the commits?

Done!

2021-08-24 18:46 UTC, marcelsavegnago commented
@hgarridoco  I didn't find anything in the code that evaluates the reach stage configured in the SLA.

2021-08-24 18:48 UTC, marcelsavegnago commented
Not that it's for this PR, but I have some demands to include in the SLA configuration:
* Minimum priority 
* Categories 
* Tags

2021-11-23 12:42 UTC, elvise commented
@DarioLodeiros any chance for this PR ?

2022-02-21 11:36 UTC, dreispt commented
/ocabot merge nobump

2022-02-21 11:56 UTC, merged