Numero en ticket portal clientes
OCA/helpdesk pull request #211
Opened 2021-04-03 01:29 UTC by PedroArroyoM

mis clientes se quejan que no saben que ticket cerre o respondi. agregue el numero del ticket en el portal de clientes para que no se pierdan, y tambien agregue una mejora en la grilla para que la linea de la tabla sea clickable

saludos

2021-04-03 01:43 UTC, marcelsavegnago commented
> mis clientes se quejan que no saben que ticket cerre o respondi. agregue el numero del ticket en el portal de clientes para que no se pierdan, y tambien agregue una mejora en la grilla para que la linea de la tabla sea clickable
> 
> saludos

Hello @PedroArroyoM. I suggest you use the English language.

2021-04-03 01:48 UTC, marcelsavegnago approved these changes

2021-04-03 01:53 UTC, marcelsavegnago requested changes

2021-04-03 01:53 UTC, marcelsavegnago commented on helpdesk_mgmt/views/helpdesk_ticket_templates.xml
> +                            <span t-esc="ticket.number"/>
```suggestion
                            <strong>Ticket:</strong><span t-esc="ticket.number" /><br/>
```

2021-04-03 08:52 UTC, pedrobaeza commented
Please squash commits into one, and put a proper commit message in English with the commit guidelines: https://www.odoo.com/documentation/14.0/reference/guidelines.html#tag-and-module-name

2021-04-09 10:05 UTC, dalonsod commented
@PedroArroyoM @marcelsavegnago could you check #212 ?

2021-12-26 20:43 UTC, closed without merging