[MIG] 14.0 helpdesk rating
OCA/helpdesk pull request #248
Opened 2021-08-02 09:35 UTC by PierrickBrun

replaces https://github.com/OCA/helpdesk/pull/193

2021-08-09 12:10 UTC, ChristianSantamaria commented
@PierrickBrun Tested on RunBot, it works fine but I found a bug in the qualification ticket template, the face statuses images,
one was not visible and one was in the wrong position.
I've been looking and in version 14 some rating images were renamed, now:
https://github.com/odoo/odoo/tree/14.0/addons/rating/static/src/img

![imagen](https://user-images.githubusercontent.com/22427989/128703715-fdc32033-fa7b-4747-b2b3-e0d17d71cc97.png)

2021-08-19 12:56 UTC, PierrickBrun commented
> @PierrickBrun Tested on RunBot, it works fine but I found a bug in the qualification ticket template, the face statuses images,
> one was not visible and one was in the wrong position.
> I've been looking and in version 14 some rating images were renamed, now:
> https://github.com/odoo/odoo/tree/14.0/addons/rating/static/src/img
> 
> ![imagen](https://user-images.githubusercontent.com/22427989/128703715-fdc32033-fa7b-4747-b2b3-e0d17d71cc97.png)

Thanks for the review !
It's fixed

2021-08-25 11:01 UTC, ChristianSantamaria reviewed
Perfect, checked the images are displayed correctly. See new comment

2021-08-25 11:01 UTC, ChristianSantamaria commented on helpdesk_mgmt_rating/models/helpdesk_ticket.py
> +        )
When giving a rating it gives an error, in v14 the rating parameter has another name.
https://github.com/odoo/odoo/blob/7015dcd56566e93418f51e8e3562f384d10b4ffa/addons/rating/models/rating_mixin.py#L172

```suggestion
    def rating_apply(self, rate, token=None, feedback=None, subtype_xmlid=None):
        return super().rating_apply(
            rate,
            token=token,
            feedback=feedback,
            subtype_xmlid="helpdesk_mgmt_rating.mt_ticket_rating",
        )
```

2021-08-31 10:15 UTC, PierrickBrun commented on helpdesk_mgmt_rating/models/helpdesk_ticket.py
> +        )
Thanks for the comment, I've fixed it and several other things

2021-09-07 08:27 UTC, PierrickBrun commented
Hi @ChristianSantamaria I think everything is fixed now

2021-09-07 09:09 UTC, ChristianSantamaria commented
Locally tested, LGTM 👍
Remember to change the commit name: 
"[IMP] helpdesk_mgmt_rating: pre-commit execution" to "[IMP] helpdesk_mgmt_rating: black, isort, prettier" 
to follow OCA standards and on the other hand perform a squash the fixes

2021-09-07 11:36 UTC, ChristianSantamaria approved these changes
👍

2021-10-04 16:03 UTC, kevinkhao requested changes
Works, but demo email is faulty. Rating needs to be 10/5/1. 5/3/1 is not supported

2021-10-04 16:19 UTC, kevinkhao commented
after discussion: the opposite is true, /rate and /rating routes in mail template were the problem

2021-10-04 16:47 UTC, kevinkhao approved these changes

2021-10-18 10:12 UTC, dreispt commented
/ocabot merge nobump

2021-10-18 10:24 UTC, merged