[15.0][ADD] helpdesk_mgmt_category_team.
OCA/helpdesk pull request #340
Opened 2022-07-08 09:15 UTC by nileshsheliya

User will set Team in Helpdesk Category. Based on that, when user create ticket from portal and select category, system auto set Team from the selected category in Ticket.

2022-11-07 11:24 UTC, jans23 commented
@pedrobaeza @DarioLodeiros Could you apply the "no stale" label, please?

2022-11-07 12:22 UTC, pedrobaeza commented
Please review it and then it can be merged.

2022-11-30 15:13 UTC, manengel requested changes
I did a review. Please fix the code quality according to my feedback.

2022-11-30 15:13 UTC, manengel commented on helpdesk_mgmt_category_team/__init__.py
> +from . import controller
Import order wrongly supplied and can be made to a one-liner. CI might report that as an error.

2022-11-30 15:13 UTC, manengel commented on helpdesk_mgmt_category_team/controller/main.py
> +from openerp.http import request
openerp? Sounds pretty obsolete to me altough it might technically work.

2022-11-30 15:13 UTC, manengel commented on helpdesk_mgmt_category_team/controller/main.py
> +from odoo.addons.helpdesk_mgmt.controllers.main import HelpdeskTicketController
Import order seems wrong to me. --> CI will complain about that.

2022-12-08 10:42 UTC, dsolanki-initos commented
Hello, @manengel I've done all the changes as per your feedback.

2023-02-07 07:37 UTC, jans23 commented
@pedrobaeza As requested, a review was performed and resulting feedback was incorporated. What else to do in order to get it merged?

2023-02-07 07:42 UTC, pedrobaeza commented
See https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#72review

You need at least 2 reviews and one coming from a PSC. You can review other PRs and ask in exchange that they review yours.

2023-08-06 12:16 UTC, closed without merging