[13.0][ADD] helpdesk_mgmt_crm: New addon.
OCA/helpdesk pull request #358
Opened 2022-08-31 10:04 UTC by victoralmau

New addon.

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT38675

2022-09-07 18:19 UTC, pedrobaeza reviewed
I think we need to add a wizard to select the sales team and/or the salesman, to get benefit of the automatic notifications provided on both of them (when you have the subtype "Opportunity created" in the sales team).

2022-09-07 18:19 UTC, pedrobaeza commented on helpdesk_mgmt_crm/__manifest__.py
> +    "name": "Helpdesk Management - Crm",
```suggestion
    "name": "Link between Helpdesk and CRM",
```

2022-09-07 18:19 UTC, pedrobaeza commented on helpdesk_mgmt_crm/__manifest__.py
> +    "version": "13.0.1.0.1",
```suggestion
    "version": "13.0.1.0.0",
```

2022-09-07 18:19 UTC, pedrobaeza commented on helpdesk_mgmt_crm/README.rst
> +This module allows you to create (and transfer messages) an opportunity from a helpdesk ticket, and keeps it linked.
```suggestion
This module allows you to convert a helpdesk ticket into an opportunity, transferring its messages,
and keeping both linked.
```

Then add a USAGE.rst file for explaining how to do the conversion.

2022-09-07 18:19 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/crm_lead.py
> +    ticket_id = fields.Many2one(comodel_name="helpdesk.ticket", string="Ticket",)
```suggestion
    ticket_id = fields.Many2one(comodel_name="helpdesk.ticket", string="Ticket")
```

2022-09-07 18:19 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/helpdesk_ticket.py
> +    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity",)
```suggestion
    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity")
```

2022-09-08 14:24 UTC, victoralmau commented
Changes done and wizard added.

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/views/helpdesk_ticket_view.xml
> +                    string="Create Lead"
```suggestion
                    string="Convert to opportunity"
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/wizard/helpdesk_ticket_create_lead.py
> +            "description": html2text.html2text(self.ticket_id.description),
```suggestion
            "description": html2text.html2text(self.ticket_id.description),
            "type": "opportunity",
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/wizard/helpdesk_ticket_create_lead_views.xml
> +                        string="Create Lead"
```suggestion
                        string="Create opportunity"
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/views/helpdesk_ticket_view.xml
> +                    name="action_open_lead"
No smart-button with the count and saying "Opportunity(ies)"?

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/wizard/helpdesk_ticket_create_lead.py
> +            "This ticket has been converted to "
```suggestion
            "This ticket has been converted to the opportunity "
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/readme/USAGE.rst
> +#. A "Opportunity" smart-button is also displayed on the ticket.
```suggestion
#. An "Opportunity" smart-button is also displayed on the ticket.
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/crm_lead.py
> +    ticket_id = fields.Many2one(comodel_name="helpdesk.ticket", string="Ticket")
```suggestion
    ticket_id = fields.Many2one(comodel_name="helpdesk.ticket", string="Helpdesk Ticket")
```

2022-09-08 14:43 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/helpdesk_ticket.py
> +    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity")
This should be a one2many.

2022-09-08 15:15 UTC, victoralmau commented on helpdesk_mgmt_crm/models/helpdesk_ticket.py
> +    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity")
Sorry, I thought this was a many2one because a ticket can only be converted into 1 lead, right?

2022-09-08 17:04 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/helpdesk_ticket.py
> +    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity")
I wouldn't restrict it. Imagine a customer asks for 3 products at the same time and you want to redirect each product to one salesman...

2022-09-08 19:19 UTC, elvise commented
@victoralmau i’m testing your PR, what happen if one ticket create 2 or more opportunities ?
I think it’s better 1 Ticket - N Opportunities 

What do you think ?

2022-09-08 19:24 UTC, pedrobaeza commented
See https://github.com/OCA/helpdesk/pull/358#discussion_r966208422 :wink:

2022-09-08 19:26 UTC, elvise commented
> See [#358 (comment)](https://github.com/OCA/helpdesk/pull/358#discussion_r966208422) 😉

Oh Sorry 😅

2022-09-09 06:06 UTC, pedrobaeza commented on helpdesk_mgmt_crm/models/helpdesk_ticket.py
> +    lead_id = fields.Many2one(comodel_name="crm.lead", string="Opportunity")
For supporting this case, let's copy the messages instead of transferring them.

2022-09-09 06:47 UTC, victoralmau commented
Changes done and one2many field added.

2022-09-09 15:32 UTC, pedrobaeza approved these changes

2022-09-09 20:38 UTC, elvise requested changes
From the user point of view i guess it’s better “Create Opportunity” instead “Convert in Opportunity”

2022-09-09 20:52 UTC, pedrobaeza commented
The text is "Convert to opportunity", and it follows the same nomenclature as leads converted to opportunity and the usual salesman pipeline.

2022-09-09 21:39 UTC, elvise commented
> The text is "Convert to opportunity", and it follows the same nomenclature as leads converted to opportunity and the usual salesman pipeline.

@pedrobaeza From this perspective looks reasonable

2022-09-09 21:40 UTC, elvise approved these changes
LGTM!

2022-09-09 21:47 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-09 21:53 UTC, merged

2023-01-11 08:37 UTC, francescapenso commented
This will be ported in 14.0 and 16?

2023-01-11 13:00 UTC, victoralmau commented
No, this module is only in v13 yet. You can migrate to higher versions if you wish.