[ADD] helpdesk_type_sla: implement rules based on type
OCA/helpdesk pull request #364
Opened 2022-09-07 13:55 UTC by BojanOD

2022-09-07 15:19 UTC, ivantodorovich approved these changes

2022-09-08 06:30 UTC, ivantodorovich requested changes

2022-09-08 06:30 UTC, ivantodorovich commented on helpdesk_type_sla/views/helpdesk_sla_views.xml
> +                <field name="type_ids" />
```suggestion
                <field name="type_ids" widget="many2many_tags" />
```

2022-09-08 07:49 UTC, elvise commented
> Implement rules based on type that depends on:
> 
> * [[IMP] helpdesk_mgmt_sla: implement more advanced rules #362](https://github.com/OCA/helpdesk/pull/362)

@BojanOD with the widget domain in this one #362 i  guess we can close this, right ?

2022-09-08 07:52 UTC, ivantodorovich commented
> with the widget domain in this one https://github.com/OCA/helpdesk/pull/362 i guess we can close this, right ?

Not sure. Some unexperienced users don't know how to use the domain widget, they might find it easier to use the field

2022-09-21 18:23 UTC, BojanOD commented
Hi @elvise @ivantodorovich 

Yes I guess we can close this PR now. Can you have a look. Thanks

2022-09-26 07:33 UTC, ivantodorovich commented on helpdesk_type_sla/views/helpdesk_sla_views.xml
> +                <field name="type_ids" />
This comment is still pending

2022-09-29 08:49 UTC, ivantodorovich commented on helpdesk_type_sla/readme/CONFIGURE.rst
> +#. Select a days or hours for that SLA.
You can drop this file, it's already described in `helpdesk_sla`

2022-09-29 08:49 UTC, ivantodorovich commented on helpdesk_type_sla/readme/DESCRIPTION.rst
> +This module adds SLA functionality in Helpdesk module.
Rewrite this, it's not accurate

2022-10-04 11:27 UTC, ivantodorovich approved these changes

2022-10-04 11:50 UTC, BojanOD commented
Hi @elvise , can you review my code. So we can merge this PR. Thank you

2022-12-22 16:59 UTC, BojanOD commented
Hi @elvise @pedrobaeza  can we close this PR

2022-12-22 17:13 UTC, pedrobaeza commented
You can close it as well clicking on the button at the footer, but why do you want to do that?

2022-12-23 08:00 UTC, elvise commented
@BojanOD Sure. 
@pedrobaeza because there is sla with domain widget

2022-12-23 08:00 UTC, pedrobaeza commented
OK, closing then.

2022-12-23 13:55 UTC, BojanOD commented
> You can close it as well clicking on the button at the footer, but why do you want to do that?

Sorry, I meant can we merge this PR @pedrobaeza

2022-12-23 15:41 UTC, pedrobaeza approved these changes
Code review

/ocabot merge nobump

2022-12-23 15:47 UTC, merged