[IMP] helpdesk_mgmt: Modernize ticket portal views
OCA/helpdesk pull request #377
Opened 2022-11-08 17:10 UTC by houzefa-abba

Bring 15.0 ticket list & form views shown in portal mode in line with those defined in the "project" module to display tasks.

While most elements remain the same, this cset also adds:
* List: group-by & search filters.
* Form: close date, assigned user, attachments.

See screenshots in https://github.com/OCA/helpdesk/pull/341#issuecomment-1240367058 for a comparison of these portal views between tickets & tasks.

Screenshots from my env, mostly demo data, hope you don't mind partial French translations:

* Ticket list, not grouped:
![Screenshot at 2022-11-08 18-05-53](https://user-images.githubusercontent.com/6347423/200629684-cd12a3cf-521a-4fd3-aba7-117be6bd5924.png)
* Ticket list, grouped by stage:
![Screenshot at 2022-11-08 18-07-28](https://user-images.githubusercontent.com/6347423/200629909-37072621-ff07-42fa-8e48-c655d2f52a72.png)
* Ticket form, not closed, has 1 attachment:
![Screenshot at 2022-11-08 18-09-38](https://user-images.githubusercontent.com/6347423/200630324-96c31793-1169-4716-a301-84d87b508fed.png)
* Ticket form, closed, multiline description with some fancy HTML, no attachments:
![Screenshot at 2022-11-08 18-08-44](https://user-images.githubusercontent.com/6347423/200630172-ae25a531-a639-4e84-8515-1eadf44103fd.png)

2022-11-09 09:10 UTC, victoralmau requested changes
Thank you, visually these changes in portal are useful.

2022-11-09 09:10 UTC, victoralmau commented on helpdesk_mgmt/controllers/myaccount.py
> -            return request.redirect("/my")
IMO this should not be removed to avoid the error.

2022-11-09 09:10 UTC, victoralmau commented on helpdesk_mgmt/controllers/myaccount.py
> +        TicketSudo = request.env["helpdesk.ticket"].sudo()
I believe that you should never use `sudo()` because you will get incorrect totals for some users.

2022-11-09 09:10 UTC, victoralmau commented on helpdesk_mgmt/controllers/myaccount.py
> +        ticket_count = TicketSudo.search_count(domain)
I believe that you should never use sudo() because you will get incorrect totals for some users.

2022-11-09 09:34 UTC, houzefa-abba commented on helpdesk_mgmt/controllers/myaccount.py
> -            return request.redirect("/my")
Thanks for the quick review

As I mentioned in the controller docstring this is inspired by the task list in the "project" module where they didn't have this; instead they filter later on with:
```python
        TicketSudo = request.env["helpdesk.ticket"].sudo()
        domain = AND(
            [
                domain,
                request.env["ir.rule"]._compute_domain(TicketSudo._name, "read"),
            ]
        )
```

This applies security rules but not ACLs. I tried disabling the ACL that gives portal users access to tickets and indeed, they can still list tickets, makes no sense. :P 

➔ I've put the redirect back & removed sudo.

I also just tried to submit a ticket with a new portal user; both portal users can't see each others' tickets now as expected.

2022-11-09 09:35 UTC, houzefa-abba commented on helpdesk_mgmt/controllers/myaccount.py
> +        TicketSudo = request.env["helpdesk.ticket"].sudo()
Resolved with https://github.com/OCA/helpdesk/pull/377#discussion_r1017687585

2022-11-09 09:35 UTC, houzefa-abba commented on helpdesk_mgmt/controllers/myaccount.py
> +        ticket_count = TicketSudo.search_count(domain)
Resolved with https://github.com/OCA/helpdesk/pull/377#discussion_r1017687585

2022-11-09 09:36 UTC, pedrobaeza commented
Please don't mix changes in the same commit and pull request. If the commit text is "Modernize ticket portal views", you can't do other changes like `sudo` or change the controller, unless it's a requirement for the views themselves.

2022-11-09 09:40 UTC, houzefa-abba commented
> Please don't mix changes in the same commit and pull request. If the commit text is "Modernize ticket portal views", you can't do other changes like `sudo` or change the controller, unless it's a requirement for the views themselves.

Controller changes here are needed to add search input & group-by which the modern view relies on.
You are right about the sudo change, it was mixed in the same place and I didn't think much about it; good thing it got caught.

2022-11-09 09:43 UTC, houzefa-abba commented
I noticed code coverage alerts in the CI - I'm thinking about adding portal tests similar to those in Odoo's project module, just not sure I'll be able to today

2022-11-09 09:44 UTC, pedrobaeza commented
That would be great, thanks.

2022-11-10 17:03 UTC, houzefa-abba commented
Rebased on top of https://github.com/OCA/helpdesk/pull/378

2022-11-15 08:13 UTC, houzefa-abba commented
In my previous rebase on https://github.com/OCA/helpdesk/pull/378 coverage tests were green but now I see they are red, I guess we were flirting with limits

I'm thinking of adding a commit to cover new filters / group-by code added in the controller

2022-11-15 14:29 UTC, pedrobaeza approved these changes

2022-11-15 14:30 UTC, pedrobaeza commented
No worry about codecov, as although interesting, it's not mandatory:

/ocabot merge major

2022-11-15 14:35 UTC, merged