[15.0][FIX+IMP] helpdesk_type: some views adjustments
OCA/helpdesk pull request #521
Opened 2023-11-01 16:49 UTC by dalonsod

Some minor adjustments for `type_id` views.

* _Location in teams `form`_. Before:
  ![imagen](https://github.com/OCA/helpdesk/assets/12749832/7f252b76-cbba-401f-bfa2-e53ee45a2e41)
  
  After:
  ![imagen](https://github.com/OCA/helpdesk/assets/12749832/1a341f2c-598b-4e6b-92b4-0e5f87b62c50)
 
* _Added to `tree` (optional) and `kanban` views_. In this one:  
  ![imagen](https://github.com/OCA/helpdesk/assets/12749832/1b45f843-71ae-4892-98fa-e3f81d067578)

2023-11-02 08:17 UTC, dalonsod commented
@BojanOD @Boxnia could you review? Thanks!

2024-01-03 10:35 UTC, moitabenfdz approved these changes
LGTM

2024-01-03 11:06 UTC, ChristianSantamaria approved these changes
LGTM 👍

2024-04-03 19:43 UTC, flotho requested changes
please rebase so that runboat will be available

2024-04-04 06:13 UTC, dalonsod commented
@flotho done!

2024-04-04 14:08 UTC, max3903 approved these changes

2024-04-05 06:31 UTC, pedrobaeza commented
Please fw-port it to upper version:

/ocabot merge minor

2024-04-05 07:33 UTC, merged