[16.0][MIG] helpdesk_mgmt_rating: Migration to 16.0
OCA/helpdesk pull request #554
Opened 2024-03-27 14:45 UTC by carolinafernandez-tecnativa

Superseed https://github.com/OCA/helpdesk/pull/484

Continue Migration to 16.0

Changes done:

 - Squash administrative commits.
 - Add noupdate=1 on post migration xml.

@Tecnativa

2024-03-27 15:14 UTC, victoralmau requested changes
I have detected an error in the `rating` module, I will check it.

Can you add some test to check that the controllers work (urls when clicking on the rating email icons) and it can be rating?

2024-03-27 15:14 UTC, victoralmau commented on helpdesk_mgmt_rating/migrations/16.0.1.0.0/post-migration.py
> +        env.cr, "helpdesk_mgmt_rating", "migrations/15.0.1.0.0/noupdate_changes.xml"
```suggestion
        env.cr, "helpdesk_mgmt_rating", "migrations/16.0.1.0.0/noupdate_changes.xml"
```

2024-03-27 15:14 UTC, victoralmau commented on helpdesk_mgmt_rating/migrations/16.0.1.0.0/noupdate_changes.xml
> +        <field name="auto_delete" eval="True" />
```suggestion
        <field
            name="email_from"
        >{{object._rating_get_operator().email_formatted}}</field>
        <field name="email_to">{{object._rating_get_partner().email_formatted}}</field>
        <field name="partner_to">{{object._rating_get_partner().id}}</field>
```
Only what really changes should be added

2024-03-27 15:14 UTC, victoralmau commented on helpdesk_mgmt_rating/tests/test_helpdesk_mgmt_rating.py
> +        )
```suggestion
from odoo.tests.common import users
from odoo.addons.base.tests.common import BaseCommon


class TestHelpdeskMgmtRating(BaseCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.partner = cls.env["res.partner"].create(
            {"name": "Test partner", "email": "test@email.com"}
        )
        new_test_user(
            cls.env,
            login="test-helpdesk-user",
            groups="helpdesk_mgmt.group_helpdesk_user",
        )
```

2024-03-27 15:22 UTC, victoralmau requested changes

2024-03-27 15:22 UTC, victoralmau commented on helpdesk_mgmt_rating/models/helpdesk_ticket.py
> +        )
```suggestion
    def rating_apply(self, rate, token=None, rating=None, feedback=None,
                     subtype_xmlid=None, notify_delay_send=False):
        return super().rating_apply(
            rate,
            token=token,
            rating=rating,
            feedback=feedback,
            subtype_xmlid="helpdesk_mgmt_rating.mt_ticket_rating",
            notify_delay_send=notify_delay_send,
        )
```

2024-03-27 15:39 UTC, carolinafernandez-tecnativa commented
> Can you add some test to check that the controllers work (urls when clicking on the rating email icons) and it can be rating?

do you have an example?

2024-03-27 15:54 UTC, victoralmau commented
> > Can you add some test to check that the controllers work (urls when clicking on the rating email icons) and it can be rating?
> 
> do you have an example?

Example: https://github.com/OCA/helpdesk/blob/16.0/helpdesk_mgmt/tests/test_helpdesk_portal.py#L108 The rating route must be set: /rate/{access_token}/5

2024-03-27 18:44 UTC, pedrobaeza commented
/ocabot migration helpdesk_mgmt_rating

2024-04-01 06:11 UTC, victoralmau requested changes

2024-04-01 06:11 UTC, victoralmau commented on helpdesk_mgmt_rating/migrations/16.0.1.0.0/noupdate_changes.xml
> +<odoo noupdate="1">
```suggestion
<odoo>
```

2024-04-01 06:11 UTC, victoralmau commented on helpdesk_mgmt_rating/migrations/16.0.1.0.0/noupdate_changes.xml
> +        <field name="partner_to">{{object._rating_get_partner().id}}</field>
You need to add `body_html` because it has been changed since version 15.0.

2024-04-01 10:28 UTC, carolinafernandez-tecnativa commented
> > > Can you add some test to check that the controllers work (urls when clicking on the rating email icons) and it can be rating?
> > 
> > 
> > do you have an example?
> 
> Example: https://github.com/OCA/helpdesk/blob/16.0/helpdesk_mgmt/tests/test_helpdesk_portal.py#L108 The rating route must be set: /rate/{access_token}/5

Added new tests, could you please check it now? Thanks!

2024-04-02 07:57 UTC, victoralmau approved these changes

2024-04-16 10:37 UTC, carolinafernandez-tecnativa commented
ping @pedrobaeza

2024-04-17 19:26 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2024-04-17 19:32 UTC, merged