[16.0]helpdesk_mgmt_project:  add ticket default company
OCA/helpdesk pull request #596
Opened 2024-07-01 19:11 UTC by flotho

supersedes https://github.com/OCA/helpdesk/pull/548/

2024-07-01 19:16 UTC, flotho commented
Hi @vincent-hatakeyama any chance to have a review here ?

2024-07-01 19:17 UTC, flotho commented
ping @DorianMag @JulienMartinez @gaelTorrecillas @GuiPrime

2024-07-02 07:11 UTC, dalonsod requested changes

2024-07-02 07:11 UTC, dalonsod commented on helpdesk_mgmt_project/models/helpdesk_ticket.py
> +    )
Attributes that don't change (like `comodel_name`, `string` or `required` shouldn't be overwritten IMO.

2024-07-02 07:11 UTC, dalonsod commented on helpdesk_mgmt_project/models/helpdesk_ticket.py
> +        for ticket in self:
`filtered` could be used here

2024-07-06 13:10 UTC, flotho commented on helpdesk_mgmt_project/models/helpdesk_ticket.py
> +        for ticket in self:
not sure because official document says it [must assign the value](https://www.odoo.com/documentation/16.0/developer/reference/backend/orm.html#computed-fields) . 
The syntax wans't more correct IMHO, so I added one assignation.
Regards

2024-07-08 15:49 UTC, dalonsod commented on helpdesk_mgmt_project/models/helpdesk_ticket.py
> +        for ticket in self:
OK, for non-stored fields I agree; for stored ones not sure (and specially for non-store and editable ones), anyway you can check adding some extra test that cover all cases.

2024-12-15 12:25 UTC, closed without merging