[12.0][ADD] Email templates for closed tickets and changed state
OCA/helpdesk pull request #78
Opened 2019-08-29 17:25 UTC by emagdalenaC2i

2019-08-29 17:27 UTC, emagdalenaC2i commented
@miguel-domatix @alvaroDomatix @SamuelDomatix and @pedrobaeza Please, could yo check this PR

2019-08-29 20:04 UTC, rvalyi requested changes

2019-08-29 20:04 UTC, rvalyi commented on helpdesk_mgmt/i18n/helpdesk_mgmt.pot
> +<<<<<<< HEAD
you committed code with a conflict!

2019-08-29 20:53 UTC, emagdalenaC2i commented on helpdesk_mgmt/i18n/helpdesk_mgmt.pot
> +<<<<<<< HEAD
fixed

2019-09-06 08:18 UTC, emagdalenaC2i commented
@miguel-domatix @alvaroDomatix @SamuelDomatix and @pedrobaeza Please, could yo check this PR

2019-09-12 09:30 UTC, emagdalenaC2i commented
@miguel-domatix please, could you review and confirm that the migration of your PR is Ok.

@alvaroDomatix @SamuelDomatix and @pedrobaeza please review this PR.
Then I will check if there is any other PR pending to migrate to v12

2019-09-12 09:35 UTC, miguel-domatix approved these changes

2019-09-12 11:02 UTC, pedrobaeza commented
@rvalyi please update your review

2019-09-17 15:13 UTC, emagdalenaC2i commented
@rvalyi please, could you update your review

2019-09-17 15:30 UTC, rvalyi approved these changes
Looks good now. Thanks!

2019-09-17 15:36 UTC, pedrobaeza commented
/ocabot merge minor

2019-09-17 15:47 UTC, merged